BinaryStudioAcademy/bsa-2025-smartscapes

- apps/frontend/src/libs/enums/app-route.enum.ts
- apps/frontend/src/pages/landing/landing.tsx
Fixed routing, added header to landing
Closes #115
> fix(frontend): fix routing ss-115

- apps/frontend/src/libs/components/button/styles.module.css
> fix(frontend): change cursor to pointer ss-109

- apps/backend/src/modules/users/user.service.ts
- packages/shared/src/modules/users/libs/enums/user-exception-message.enum.ts
> fix(backend): change error message for user with same email ss-134

- apps/backend/src/libs/modules/plugins/auth/auth-plugin.test.ts
- apps/backend/src/libs/modules/plugins/auth/libs/helpers/check-is-white-route.helper.ts
- apps/backend/src/libs/modules/server-application/base-server-application-api.ts
- eslint.config.ts
https://github.com/BinaryStudioAcademy/bsa-2025-smartscapes/issues/148
> fix(backend): fix white listing rules ss-148

- apps/backend/src/modules/auth/auth.controller.ts
> fix(backend): update swagger sign-in response example ss-221

- apps/backend/src/modules/notifications/notification.controller.ts
fix swagger documentation for notifications
> fix(backend): introduce swagger doc for dto in notifications ss-229

- apps/backend/src/modules/notifications/notification.controller.ts
add security to swagger documentation of notifications
> feat(backend): add security to swagger documentation of notifications ss-233

- apps/backend/src/modules/reviews/review.controller.ts
Update review request Dto in swagger docs 
Closes #251
> fix(backend): update reviews module swagger docs ss-251

- readme.md
Resolves #272 
- Added missing closing curly bracket to `reviews` table;
- Fixed code indentation
> fix(root): fix database erDiagram ss-272

- apps/backend/src/modules/user-follows/user-follows.controller.ts
Changes:
-   Fixes swagger docs
> fix(backend): format swagger docs ss-285

- apps/backend/src/modules/notifications/notification.controller.ts
Updated notification swagger: added data wrapper, changed properties order in response dto
Closes #279
> fix(backend): update notification swagger response dto ss-279

- apps/frontend/tsconfig.json
> fix(frontend): increase cache file size ss-295

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/integration-tests.yml
> fix(root): fix integration tests workflow ss-291

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/integration-tests.yml
> 291 fix integration tests workflow

- apps/backend/src/modules/routes/route.repository.ts
- readme.md
Updates:
- Fixes db queries of routes repository
> fix(backend): fix routes repository queries ss-432

- apps/backend/src/libs/modules/aws/base-aws-file.module.ts
- apps/backend/src/modules/auth/auth.service.ts
- apps/backend/src/modules/categories/category.entity.ts
- apps/backend/src/modules/categories/category.model.ts
- apps/backend/src/modules/files/files.entity.ts
- apps/backend/src/modules/files/files.model.ts
- apps/backend/src/modules/files/files.service.ts
- apps/backend/src/modules/groups/group.entity.ts
- apps/backend/src/modules/notifications/notification.model.ts
- apps/backend/src/modules/permission/permission.entity.ts
- apps/backend/src/modules/planned-paths/planned-path.entity.ts
- apps/backend/src/modules/planned-paths/planned-path.model.ts
- apps/backend/src/modules/points-of-interest/points-of-interest.entity.ts
- apps/backend/src/modules/points-of-interest/points-of-interest.model.ts
- apps/backend/src/modules/reviews/review.entity.ts
- apps/backend/src/modules/reviews/review.model.ts
- apps/backend/src/modules/reviews/review.service.ts
- apps/backend/src/modules/routes/route.entity.ts
- apps/backend/src/modules/routes/route.model.ts
- apps/backend/src/modules/routes/route.repository.ts
- apps/backend/src/modules/routes/route.service.ts
- apps/backend/src/modules/user-follows/user-follows.entity.ts
- apps/backend/src/modules/users/user.service.ts
- apps/frontend/src/libs/modules/map-client/map-client.module.ts
- apps/frontend/src/modules/auth/auth-api.ts
- eslint.config.ts
- tests/api/controllers/api-controller.ts
> chore(root): add lines-between-class-members eslint rule ss-463

- apps/frontend/src/libs/components/sidebar/styles.module.css
> fix(frontend): apply higher z index value for sidebar then routes panel ss-485

- apps/backend/src/modules/files/files.service.ts
- apps/backend/src/modules/files/libs/enums/file-exeption-message.enum.ts
- apps/frontend/src/libs/components/carousel/libs/hooks/use-carousel-wheel-event.hook.ts
- fix upload max size message 
- carousel wheel event
Resolves #434 
https://github.com/user-attachments/assets/6ee8aca8-062b-403f-92ee-171890e73382
> fix(frontend/backend): fix upload max size message and carousel wheel event ss-434

- apps/frontend/src/libs/components/review-card/review-card.tsx
- apps/frontend/src/libs/components/review-card/styles.module.css
The following functionality have been implemented:
- when user clicks on name or avatar in the review block, redirect to user public profile
> feat(frontend): redirect to user public profile on avatar and name click in review ss-582

- apps/backend/src/modules/notifications/notification.repository.ts
- apps/backend/src/modules/routes/route.repository.ts
- apps/backend/src/modules/user-routes/user-route.repository.ts
https://github.com/user-attachments/assets/0224fa3d-cafb-4947-b40f-f111f950e815
Closure #605
> fix(backend): fix pois order ss-605

- apps/backend/src/modules/routes/route.repository.ts
- apps/frontend/src/libs/modules/map-client/map-client.module.ts
resolves https://github.com/BinaryStudioAcademy/bsa-2025-smartscapes/issues/646
> fix(frontend): fit to coordinates check ss-646
